(define(problem barman)
(:domain barman)
(:init
(not (holding))
(empty)
(not (containIg1))
(not (containIg2))
(not (containIg3))
(not (containIg4))
(not (containIg5))
(not (containCt))
( = (numg) 5)
( = (numig1) 5)
( = (numig2) 5)
( = (numig3) 5)
( = (numig4) 5)
( = (numig5) 5)
( = (numct) 5)
)
(:goal(and(=(numct)0)(empty)(not(holding))))
)