(define (problem pro-Diagonal-Return)
        (:domain Diagonal-Return)
        (:init
            (and
              (dectl)
              (not (dectr))
              (not (dectt))
              (not (dectb))
              (not (visitlt))
              (not (visitrt))
              (not (visitrb))
              (>= (disr) 0)
              (>= (disl) 0)
              (>= (dist) 0)
              (>= (disb) 0)
              (>= (startl) 0)
              (>= (startt) 0)
              (= (startl) (disl))
              (= (startt) (dist))
            )
        )
        (:goal (and
                   (visitlt)
                   (visitrt)
                   (visitrb)
                   (= (disl) (startl))
                   (= (dist) (startt))
               )
        )
)