(define(problem pro-Hall-A)
(:domain Hall-A)
(:init
(not (visitlt))
(not (visitrt))
(not (visitlb))
(not (visitrb))
( = (disl) 3)
( = (dist) 5)
( = (disb) 6)
( = (startt) 5)
( = (startl) 3)
( = (disr) 0)
)
(:goal(and(visitrt)(visitlt)(visitlb)(visitrb)(=(disl)(startl))(=(dist)(startt))))
)