(define(problem pro-Diagonal-Return)
(:domain Diagonal-Return)
(:init
(not (visitlt))
(not (visitrt))
(not (visitrb))
( = (disr) 3)
( = (disl) 3)
( = (dist) 3)
( = (disb) 3)
( = (startt) 3)
( = (startl) 3)
)
(:goal(and(visitlt)(visitrt)(visitrb)(=(disl)(startl))(=(dist)(startt))))
)