(define(problem pro-Diagonal-Return)
(:domain Diagonal-Return)
(:init
(not (visitlt))
(not (visitrt))
(not (visitrb))
( = (disr) 5)
( = (disl) 5)
( = (dist) 4)
( = (disb) 5)
( = (startt) 4)
( = (startl) 5)
)
(:goal(and(visitlt)(visitrt)(visitrb)(=(disl)(startl))(=(dist)(startt))))
)