(define(problem pro-Diagonal-Return)
(:domain Diagonal-Return)
(:init
(not (dectr))
(dectl)
(not (dectt))
(not (dectb))
(not (visitlt))
(not (visitrt))
(not (visitrb))
( = (disr) 0)
( = (disl) 0)
( = (dist) 1)
( = (disb) 0)
( = (startt) 1)
( = (startl) 0)
)
(:goal(and(visitlt)(visitrt)(visitrb)(=(disl)(startl))(=(dist)(startt))))
)